### ISSUE TITLE
同学您好， 想请教下一些问题

### ISSUE THREAD

**Issue by FrancoisMoreau** [JoeyChuuichi/MachineVisionIntern#1]
同学你好， 我正在申请IME的项目。 目前在申请过程中， 对IME一些流程尚且不够熟悉， 方便加一下微信， 问一些申请的问题吗？
十分感谢。

**Comment by JoeyChuuichi** [comment]
Sorry for the late reply.

You can go to the IME website and send the email to the officers if you have any questions about the application. They are both quite kind ladies!

If you are interested in our lab, you are more than welcomed to join in our lab. But I don't want to put my private account here. So please give me your contact number, I will contact you ASAP.

**Comment by FrancoisMoreau** [comment]
Thank you.
可以加一下我微信吗： 15558000103
想具体问一下那边的情况呢。 多谢！
